version: '3.8'

services:

  db:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=flushdb,flushall

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - db
    command: npm start