version: "3.8"

services:
  db:
    image: mongo:${MONGO_VERSION}
    container_name: db
    networks:
      - net_A
    volumes:
      - zad1_mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  server:
    image: oworobjew/stepik:latest
    container_name: server
    networks:
      - net_A
    ports:
      - "3003:3003"
    depends_on:
      - db

networks:
  net_A:

volumes:
  zad1_mongo_data:
    external: true
