version: "3.8"

services:

  database:
    image: mongo:4.1.13
    container_name: database
    networks:
      - backend_network
    volumes:
      - lab6_mongo:/data/db
    ports:
      - "27017:27017"
      

  backend:
    build: server
    container_name: backend
    networks:
      - backend_network
      - frontend_network
    ports:
      - "3001:3001"
    depends_on:
      - database

  frontend:
    build: client
    container_name: frontend
    networks:
      - frontend_network
    ports:
      - "3000:3000"
    depends_on:
      - database
      - backend
    

networks:
  frontend_network:
  backend_network:
    internal: true

volumes:
  lab6_mongo: