version: "3.8"

services:

  db:
    image: mysql
    container_name: db
    networks:
      - my_network
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend
    networks:
      - backend_network
    environment:
      DB_HOST: db
    ports:
      - "80:3000"
    depends_on:
      - db
    

networks:
  frontend_network:
  backend_network:
    internal: true

volumes:
  db_data: