version: '3.8'

services:

  backend:
    build: app
    environment:
      DB_HOST: postgresdb
      DB_USER: admin
      DB_PASSWORD: admin
      DB_PORT: 5432
      DB_NAME: pgdb 
      REDIS_URL: "redis://redisdb:6379"
    depends_on:
      - redisdb
      - postgresdb
    restart: 
      on-failure

  redisdb:
    image: redis

  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pgdb
    volumes:
      - lab8zad3:/data/db
  
  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  lab8zad3: